version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=jeff
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

volumes:
  progresDB:

